services:
  postgres:
    image: debezium/postgres:15
    environment:
      - POSTGRES_DB=yarmaq_accounts
      - POSTGRES_USER=danial
      - POSTGRES_PASSWORD=yarmaq_pass
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d 
    command: ["postgres", "-c", "wal_level=logical"]